#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pyyaml>=6.0",
# ]
# ///
"""
ollama-sync.py - reconcile ollama tags with on-disk Modelfiles,
                 gated by ollama-compose.yml.

Source of truth: ollama-compose.yml (top-level keys: personas, defaults, models).
State file:      .sync-state.json (sha256 of each rendered Modelfile, keyed by tag).
Custom-tag regex: ^(coder|planner|architect)-agent-  (anything else is a base
                  model and is never touched).

Flags:
  --dry-run         print plan, mutate nothing
  --prune           remove drift tags (custom tags not in YAML, or enabled:false)
  --only <substr>   restrict to entries whose tag or modelfile path contains <substr>
  -h / --help       show this help

Schema reference: /home/nick/.claude/plans/personas-and-defaults-schema.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NoReturn, Self

CUSTOM_TAG_RE = re.compile(r"^(coder|planner|architect)-agent-")
HEADER = "# Generated by ollama-sync.py from ollama-compose.yml -- do not edit"

# Param groups for stable render layout. Keys in the same group are emitted
# contiguously with no blank line between them; groups are separated by blank
# lines. `num_ctx` is per-model and emitted first (outside the defaults dict).
PARAM_GROUPS: list[list[str]] = [
    ["num_predict", "temperature", "min_p", "top_k", "top_p"],
    ["repeat_penalty", "presence_penalty"],
    ["stop"],
]


@dataclass(frozen=True)
class ModelSpec:
    """Represents a single model definition from the YAML (validated)."""

    tag: str
    enabled: bool
    role: str
    base: str | None = None
    num_ctx: int | None = None
    persona: str | None = None
    params: dict[str, Any] | None = None
    modelfile: str | None = None
    template: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Self:
        """Create a ModelSpec from a YAML entry dict."""
        return cls(
            tag=data["tag"],
            enabled=data.get("enabled", False),
            role=data.get("role", "agent"),
            base=data.get("base") if data.get("enabled", False) else None,
            num_ctx=data.get("num_ctx") if data.get("enabled", False) else None,
            persona=data.get("persona") if data.get("enabled", False) else None,
            params=data.get("params") if data.get("enabled", False) else None,
            modelfile=data.get("modelfile") if data.get("enabled", False) else None,
            template=data.get("template") if data.get("enabled", False) else None,
        )


@dataclass(frozen=True)
class BuildTarget:
    """Represents a model that needs to be created (tag, rendered bytes, hash, path)."""

    tag: str
    rendered: bytes
    hash: str
    mf_rel: str


@dataclass(frozen=True)
class BuildPlan:
    """A structured object containing the final decision for every model."""

    to_create: list[BuildTarget]
    to_remove: list[tuple[str, str]]
    to_skip: list[str]
    failures: list[tuple[str, str]]


@dataclass(frozen=True)
class Manifest:
    """A container for the validated models, personas, and defaults_by_role."""

    version: int
    personas: dict[str, str]
    defaults_by_role: dict[str, dict[str, Any]]
    model_specs: list[ModelSpec]

    @classmethod
    def from_compose(cls, compose_data: dict[str, Any]) -> "Manifest":
        """Create a Manifest from loaded YAML compose data."""
        if compose_data.get("version") != 1:
            errorout(f"Unsupported schema version: {compose_data.get('version')}")

        personas = compose_data.get("personas", {})
        defaults = compose_data.get("defaults", {})
        models = compose_data.get("models", [])

        # Validate and convert model entries to ModelSpecs
        model_specs: list[ModelSpec] = []
        for entry in models:
            try:
                spec = ModelSpec.from_dict(entry)
                model_specs.append(spec)
            except (KeyError, ValueError) as ex:
                errorout(f"Invalid model entry {entry.get('tag', '?')}: {ex}")

        return cls(
            version=compose_data.get("version", 1),
            personas=personas,
            defaults_by_role=defaults,
            model_specs=model_specs,
        )


def errorout(msg: str, code: int = 2) -> NoReturn:
    """Print an error message to stderr and exit with the given code."""
    print(msg, file=sys.stderr)
    sys.exit(code)


def require_tool(name: str) -> None:
    if shutil.which(name) is None:
        errorout(f"{name} required on PATH", 3)


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def ollama_list() -> list[str]:
    out = subprocess.run(
        ["ollama", "list"], capture_output=True, text=True, check=True
    ).stdout
    return [line.split()[0] for line in out.splitlines()[1:] if line.strip()]


def run_ollama(
    args: list[str], dry_run: bool = False, stream_stdout: bool = False
) -> tuple[int, str]:
    """Centralized subprocess wrapper for ollama commands."""
    if dry_run:
        return 0, ""

    result = subprocess.run(
        ["ollama"] + args,
        stdout=None if stream_stdout else subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.returncode, result.stderr.strip()


def resolve_effective_params(
    model_spec: ModelSpec, defaults_by_role: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    """Merge role-based defaults with model-specific params."""
    if not model_spec.enabled:
        return {}

    # Get role-specific defaults
    role_defaults = defaults_by_role.get(model_spec.role, {})

    # Start with role defaults
    effective_params = role_defaults.copy()

    # Override with model-specific params if present
    if model_spec.params:
        effective_params.update(model_spec.params)

    return effective_params


def render_parameter_lines(effective_params: dict[str, Any]) -> list[str]:
    """Render parameter lines in canonical group order."""
    lines: list[str] = []

    for group in PARAM_GROUPS:
        group_lines: list[str] = []
        for key in group:
            if key not in effective_params:
                continue
            val = effective_params[key]
            match val:
                case list() as val if key == "stop":
                    if not val:
                        continue
                    for tok in val:
                        # Escape double quotes within stop tokens.
                        escaped_tok = str(tok).replace('"', '\\"')
                        group_lines.append(f'PARAMETER stop "{escaped_tok}"')
                case str() | int() | float() as val:
                    group_lines.append(f"PARAMETER {key} {val}")
                case _:
                    # Fallback or error handling if needed
                    pass
        if not group_lines:
            continue
        lines.extend(group_lines)

    return lines


def render_modelfile(
    model_spec: ModelSpec,
    personas: dict[str, str],
    defaults_by_role: dict[str, dict[str, Any]],
) -> bytes:
    """Render a Modelfile from a ModelSpec. Pure; same input -> same bytes."""
    if not model_spec.enabled:
        raise ValueError(f"Cannot render disabled model {model_spec.tag}")

    # num_ctx is special and emitted first. Use entry or role defaults.
    effective_params = resolve_effective_params(model_spec, defaults_by_role)

    if (num_ctx := model_spec.num_ctx or effective_params.get("num_ctx")) is None:
        raise ValueError(f"num_ctx not found in entry or defaults for {model_spec.tag}")
    num_ctx = int(num_ctx)

    # Resolve persona
    if model_spec.persona and model_spec.persona in personas:
        persona = personas[model_spec.persona]
    elif model_spec.persona:
        persona = model_spec.persona
    else:
        raise ValueError(f"persona not found for {model_spec.tag}")

    # Sanitize persona to prevent Modelfile injection via triple quotes.
    persona = persona.replace('"""', '\\"""')

    parts: list[str] = [
        HEADER,
        "",
        f"FROM {model_spec.base}",
    ]

    if template := model_spec.template:
        sanitized_template = template.replace('"""', '\\"""')
        parts.append(f'TEMPLATE """{sanitized_template}"""')
        parts.append("")

    parts.append("")
    parts.append(f"# {model_spec.role} agent on {model_spec.base}")
    parts.append(f"PARAMETER num_ctx {num_ctx}")

    # Emit params in the canonical group order.
    param_lines = render_parameter_lines(effective_params)
    if param_lines:
        parts.extend(param_lines)

    parts.append("")
    parts.append('SYSTEM """')
    parts.append(persona)
    parts.append('"""')
    parts.append("")  # trailing newline
    return ("\n".join(parts)).encode("utf-8")


def load_compose(p: Path) -> dict[str, Any]:
    import yaml  # PEP 723 dep

    data = yaml.safe_load(p.read_text())
    match data:
        case {"models": list(), "personas": dict(), "defaults": dict()}:
            return data
        case _:
            errorout(
                f"{p}: invalid structure (must be dict with 'models' list, 'personas' dict, and 'defaults' dict)"
            )


def load_state(p: Path) -> dict[str, str]:
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        return {}


def save_state(p: Path, state: dict[str, str], have: set[str]) -> None:
    pruned = {k: v for k, v in state.items() if k in have}
    p.write_text(json.dumps(pruned, indent=2, sort_keys=True) + "\n")


def plan_phase(
    manifest: Manifest, current_tags: set[str], state: dict[str, str]
) -> BuildPlan:
    """Phase B: Planning (The Reconciler). Pure function."""
    to_create: list[BuildTarget] = []
    to_remove: list[tuple[str, str]] = []
    to_skip: list[str] = []
    failures: list[tuple[str, str]] = []

    for spec in manifest.model_specs:
        if not spec.enabled:
            if spec.tag in current_tags:
                to_remove.append((spec.tag, "disabled in YAML"))
            continue

        try:
            rendered = render_modelfile(
                spec, manifest.personas, manifest.defaults_by_role
            )
            h = sha256_bytes(rendered)

            if state.get(spec.tag) == h and spec.tag in current_tags:
                to_skip.append(spec.tag)
                continue

            to_create.append(
                BuildTarget(
                    tag=spec.tag, rendered=rendered, hash=h, mf_rel=spec.modelfile or ""
                )
            )
        except (KeyError, ValueError) as ex:
            failures.append((spec.tag, str(ex)))

    # Scan for custom tags in ollama list that are undeclared in YAML
    for tag in current_tags:
        if not CUSTOM_TAG_RE.match(tag):
            continue
        if any(spec.tag == tag for spec in manifest.model_specs):
            continue
        to_remove.append((tag, "undeclared in YAML"))

    return BuildPlan(
        to_create=to_create, to_remove=to_remove, to_skip=to_skip, failures=failures
    )


def apply_phase(
    plan: BuildPlan,
    root: Path,
    dry_run: bool,
    state: dict[str, str],
    have_set: set[str],
) -> tuple[dict[str, str], list[str], list[tuple[str, str]]]:
    """Phase C: Application (The Executor)."""
    created: list[str] = []
    failed: list[tuple[str, str]] = []

    for target in plan.to_create:
        mf_path = root / (
            target.mf_rel or f"{target.tag.replace(':', '_')}/Modelfile"
        )
        mf_path.parent.mkdir(parents=True, exist_ok=True)

        if dry_run:
            print(f"create {target.tag}  (rendered to {target.mf_rel})")
            created.append(target.tag)
            state[target.tag] = target.hash
            continue

        mf_path.write_bytes(target.rendered)
        print(f"SYNCING {target.tag}", flush=True)

        # Keep Ollama's native pull progress visible; capture stderr for errors.
        returncode, stderr = run_ollama(
            ["create", target.tag, "-f", str(mf_path)], stream_stdout=True
        )
        print()

        if returncode == 0:
            state[target.tag] = target.hash
            created.append(target.tag)
        else:
            failed.append((target.tag, stderr or f"exit {returncode}"))

    # Handle removals
    for tag, reason in plan.to_remove:
        if dry_run:
            print(f"rm     {tag}  ({reason})")
            state.pop(tag, None)
        else:
            returncode, stderr = run_ollama(["rm", tag], dry_run)
            if returncode != 0:
                failed.append((tag, f"ollama rm failed: {stderr or 'unknown error'}"))
            else:
                state.pop(tag, None)

    return state, created, failed


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Reconcile ollama tags with on-disk Modelfiles."
    )
    ap.add_argument("--dry-run", action="store_true", help="print plan, mutate nothing")
    ap.add_argument("--prune", action="store_true", help="remove drift tags")
    ap.add_argument(
        "--only", metavar="SUBSTR", default="", help="filter by tag or path substring"
    )
    ap.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="root of the custom_models tree (default: script dir)",
    )
    args = ap.parse_args()

    require_tool("ollama")

    root: Path = args.root
    compose_p = root / "ollama-compose.yml"
    state_p = root / ".sync-state.json"
    if not compose_p.exists():
        errorout(f"missing {compose_p}")

    # Phase A: Load & Validate
    compose = load_compose(compose_p)
    manifest = Manifest.from_compose(compose)

    # Load current state and ollama list
    state = load_state(state_p)
    have = ollama_list()
    have_set = set(have)

    # Phase B: Planning (The Reconciler)
    plan = plan_phase(manifest, have_set, state)

    # Filter plan based on --only flag
    if args.only:
        plan = BuildPlan(
            to_create=[
                t
                for t in plan.to_create
                if args.only in t.tag or (t.mf_rel and args.only in t.mf_rel)
            ],
            to_remove=[r for r in plan.to_remove if args.only in r[0]],
            to_skip=plan.to_skip,
            failures=plan.failures,
        )

    # Phase C: Application (The Executor)
    state, created, failed = apply_phase(plan, root, args.dry_run, state, have_set)

    # Phase D: Persistence
    if not args.dry_run:
        save_state(state_p, state, have_set)

    print("-" * 72)
    print("RESULTS")
    print(
        f"created {len(created)}  skipped {len(plan.to_skip)}  "
        f"failed {len(plan.failures + failed)}  drift {len(plan.to_remove)}"
    )
    if plan.to_remove:
        print("drift:")
        for tag, why in plan.to_remove:
            print(f"  - {tag} ({why})")
        if not args.prune:
            print("  (run with --prune to remove)")
    if args.dry_run:
        print("(dry run; no changes made)")

    return 1 if plan.failures or failed else 0


if __name__ == "__main__":
    sys.exit(main())
